services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: fatihoune
      POSTGRES_PASSWORD: 669255
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
